<a href="https://colab.research.google.com/github/NoeGille/UNet-on-fashion-mnist/blob/main/learning_PyTorch_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learning Pytorch

The goal of this notebook is to learn PyTorch.

In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt

## Tensor operation

In [3]:
# Creating a tensor
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(my_tensor)

# We can set the device
device = "cuda" if torch.cuda.is_available() else "cpu"

# Requires_grad if the tensor requires gradient (useful for retropropagation)
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, requires_grad=True)

print(my_tensor)
print(my_tensor.shape)

# Other common initialization methods (same as numpy)
x = torch.empty(size = (3, 3))
x = torch.zeros((3, 3))
x = torch.rand((3, 3))
x = torch.ones((3,3))
x = torch.eye(5)
x = torch.arange(start=0, end=5, step=1)
x = torch.linspace(0, 5, 10)

# Normalize values
x = torch.empty(size=(1, 5)).normal_(mean=0,std=1)

# Change tensor types
tensor = torch.arange(4)
print(tensor.float())
print(tensor.bool())

# Numpy to tensor
tensor = torch.from_numpy(np.ones((3,3)))
np_array_back = tensor.numpy()
print(np_array_back)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.Size([2, 3])
tensor([0., 1., 2., 3.])
tensor([False,  True,  True,  True])
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# Operations (very close to numpy)

x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

# Matrix addition
t = torch.zeros((3))
t.add_(x)
print(t)

# Matrix comparaison
z = x > 0
# Element wise comparison between two matrix / vectors
z = torch.eq(x, y)

# Matrix multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1, x2)

# element wise multiplication
z = x * y

# dot product
z = torch.dot(x, y)
print(z)

# Batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m ,p))
out_bmm = torch.bmm(tensor1, tensor2)

print(out_bmm.shape)

# Example of broadcasting
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))

z = x1 - x2
# Do the operation on every rows
# this is called broadcasting (diffusion en français)

# Othre useful operations
values,indices = torch.max(x, dim=0)

print(values, indices)

# Torch requires x to be a float tensor
mean = torch.mean(x.float())

sorted_y, indices = torch.sort(y, dim=0, descending=False)

# Limit the value range within min and max value
z = torch.clamp(y, min=0, max=5)
print(z)

# Boolean tensor operations
x = torch.tensor([1,0,1,1,1], dtype=torch.bool)
z = torch.any(x)
z = torch.all(x)

tensor([1., 2., 3.])
tensor(46)
torch.Size([32, 10, 30])
tensor(3) tensor(2)
tensor([5, 5, 5])


## Tensor indexing

In [32]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

print(x[0].shape) # x[0,:]
print(x[:, 0].shape) # first feature of each example
print(x[2,:10]) # Basically the same as numpy

x[0, 0] = 100

# Advanced indexing
x = torch.arange(10)
print(x[(x < 2) | (x > 8)])
# remainder (reste en français) <=> %
print(x[x.remainder(2) == 0])
# Same as np.where
print(torch.where(x > 5, x, x * 2))


torch.Size([25])
torch.Size([10])
tensor([0.7494, 0.4575, 0.8094, 0.6843, 0.7558, 0.9981, 0.2555, 0.9965, 0.6041,
        0.4982])
tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
1


## Tensor reshaping


In [57]:
x = torch.arange(9)

x_3x3 = x.view(3, 3)

x_3x3 = x.reshape(3, 3)
print(x_3x3)

y = x_3x3.t()
print(x_3x3)
print(y.contiguous().view(9))

x1 = torch.rand((2, 5))
x2 = torch.rand((2,5))
print(torch.cat((x1, x2), dim=0))
print(torch.cat((x1, x2), dim=1))

# -1 to get a flatten
z = x1.view(-1)
print(z)

# Flatten for each example
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(z.shape)

# switch between dimension dimensions
z = x.permute(0, 2, 1) 
print(z.shape)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
tensor([[6.9497e-01, 9.3705e-01, 8.8954e-04, 2.2306e-01, 4.9460e-01],
        [3.6968e-01, 9.8840e-01, 1.7047e-01, 5.1732e-01, 2.1394e-01],
        [3.2850e-02, 2.6337e-01, 8.9324e-01, 3.3837e-01, 8.7981e-01],
        [8.4975e-01, 2.3972e-01, 8.9363e-01, 8.8074e-01, 5.1366e-01]])
tensor([[6.9497e-01, 9.3705e-01, 8.8954e-04, 2.2306e-01, 4.9460e-01, 3.2850e-02,
         2.6337e-01, 8.9324e-01, 3.3837e-01, 8.7981e-01],
        [3.6968e-01, 9.8840e-01, 1.7047e-01, 5.1732e-01, 2.1394e-01, 8.4975e-01,
         2.3972e-01, 8.9363e-01, 8.8074e-01, 5.1366e-01]])
tensor([6.9497e-01, 9.3705e-01, 8.8954e-04, 2.2306e-01, 4.9460e-01, 3.6968e-01,
        9.8840e-01, 1.7047e-01, 5.1732e-01, 2.1394e-01])
torch.Size([64, 10])
torch.Size([64, 5, 2])
