<a href="https://colab.research.google.com/github/NoeGille/UNet-on-fashion-mnist/blob/main/learning_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learning Pytorch

The goal of this notebook is to learn PyTorch.

In [20]:
import torch
import numpy as np
import matplotlib.pyplot as plt

## Tensor operation

In [23]:
# Creating a tensor
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(my_tensor)

# We can set the device
device = "cuda" if torch.cuda.is_available() else "cpu"

# Requires_grad if the tensor requires gradient (useful for retropropagation)
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, requires_grad=True)

print(my_tensor)
print(my_tensor.shape)

# Other common initialization methods (same as numpy)
x = torch.empty(size = (3, 3))
x = torch.zeros((3, 3))
x = torch.rand((3, 3))
x = torch.ones((3,3))
x = torch.eye(5)
x = torch.arange(start=0, end=5, step=1)
x = torch.linspace(0, 5, 10)

# Normalize values
x = torch.empty(size=(1, 5)).normal_(mean=0,std=1)

# Change tensor types
tensor = torch.arange(4)
print(tensor.float())
print(tensor.bool())

# Numpy to tensor
tensor = torch.from_numpy(np.ones((3,3)))
np_array_back = tensor.numpy()
print(np_array_back)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.Size([2, 3])
tensor([0., 1., 2., 3.])
tensor([False,  True,  True,  True])
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
# Operations

x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

t = torch.zeros((3))
t.add_(x)
print(t)

tensor([1., 2., 3.])
